{% set name = "xdoctest" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2eac8131bdcdf2781b4e5a62d6de87f044b730cc8db8af142a51bb29c245e779

build:
  noarch: python
  number: 0
  entry_points:
    - xdoctest = xdoctest.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - six

test:
  imports:
    - xdoctest
    - xdoctest.docstr
    - xdoctest.utils
  commands:
    - xdoctest --help

about:
  home: https://github.com/Erotemic/xdoctest
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A rewrite of Python's builtin doctest module without all the weirdness (with pytest plugin integration)
  description: |
    The xdoctest package is a re-write of Python's builtin doctest module.
    It replaces the old regex-based parser with a new abstract-syntax-tree
    based parser (using Python's ast module). The goal is to make doctests
    easier to write, simpler to configure, and encourage the pattern of test
    driven development.
  doc_url: http://xdoctest.readthedocs.io/
  dev_url: https://github.com/Erotemic/xdoctest

extra:
  recipe-maintainers:
    - mdraw
